---
title: "tarea2"
format: html
editor: visual
---


```{r}
#| message: false
#| warning: false

library(tidyverse)
library(ggplot2)
library(readr)
library(plotly)
library(DT)
library(dplyr)
```

```{r}
#| message: false
#| warning: false

# Carga del archivo CSV de entrada en un dataframe
# con la función read_delim() de readr
covid_general <-
  read_delim(
    file = "D:/1semestre/programacion/tarea2/05_30_22_CSV_GENERAL.csv",
    col_select = c(
      "FECHA",
      "hom_posi",
      "muj_posi",
      "menor_posi",
      "adul_posi",
      "am_posi",
      "nue_posi"
    ) 
  )

# Cambio de nombre de columnas
covid_general <-
  covid_general |>
  rename(
    #fecha = FECHA,
    positivos_hombres = hom_posi,
    positvos_mujeres = muj_posi,
    positivos_menores = menor_posi,
    positivos_adultos = adul_posi,
    positivos_mayores = am_posi,
    positivos_nuevos = nue_posi
  )

# Cambio de tipo de datos de la columna fecha, de str a date
covid_general <-
  covid_general |>
  mutate(FECHA = as.Date(FECHA, format = "%d/%m/%Y"))
```
```{r}
# Tabla de datos de COVID generales
covid_general |>
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```
```{r}
grafico_barras_ggplot2 <-
  covid_general|>
  ggplot(aes(y= positivos_nuevos, x=FECHA)) +
 geom_col() +
  ggtitle ("Cantidad de Casos Positivos Nuevos por Día")+
  xlab("Fecha")+
  ylab("Nuevos Casos")

ggplotly(grafico_barras_ggplot2) |> 
  config(locale = 'es')

```
```{r}
# Gráfico de líneas con la evolución de los casos de COVID
grafico_lineas_ggplot2 <-
  covid_general |>
  ggplot(aes(x = FECHA, y = value, color = variable)) +
  geom_line(aes(y = positivos_hombres, color = "Hombres")) +
  geom_line(aes(y = positvos_mujeres, color = "Mujeres")) +
  scale_color_manual( # colores
    "",
    values = c(
      "Hombres" = "blue",
      "Mujeres" = "green"
    )
  ) +
  ggtitle("Evolución de los Casos Positivos") +
  xlab("Fecha") +
  ylab("Casos Positivos") 
    

# Gráfico de dispersión plotly
ggplotly(grafico_lineas_ggplot2) |>
  config(locale = 'es')
```
```{r}
# Gráfico de líneas con la evolución de los casos de COVID
grafico_lineas_ggplot2 <-
  covid_general |>
  ggplot(aes(x = FECHA, y = value, color = variable)) +
  geom_line(aes(y = positivos_menores, color = "Menores")) +
  geom_line(aes(y = positivos_adultos, color = "Adultos")) +
  geom_line(aes(y = positivos_mayores, color = "Adultos Mayores")) +
  scale_color_manual( # colores
    "",
    values = c(
      "Menores" = "blue",
      "Adultos" = "green",
      "Adultos Mayores" = "red"
    )
  ) +
  ggtitle("Evolución de los Casos Positivos") +
  xlab("Fecha") +
  ylab("Casos Positivos") 
    

# Gráfico de dispersión plotly
ggplotly(grafico_lineas_ggplot2) |>
  config(locale = 'es')
```
```{r}
covid_cantonal_positivos <-
  read_delim(
    file = "D:/1semestre/programacion/tarea2/05_30_22_CSV_POSITIVOS.csv",
    locale = locale(encoding = "WINDOWS-1252"),
    col_select = c("provincia", "canton", "30/05/2022")
  )

# Cambio de nombre de columnas
covid_cantonal_positivos <-
  covid_cantonal_positivos |>
  rename(
    positivos = '30/05/2022'
  )

# Borrado de filas con valor NA u "Otros"
# en la columna canton
covid_cantonal_positivos <-
  covid_cantonal_positivos |>
   filter(!is.na(canton) & canton != "Otros")

# Tabla de datos de COVID cantonales positivos
covid_cantonal_positivos |>
  datatable(options = list(
    pageLength = 5,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```
```{r}
histograma_ggplot2 <-
covid_cantonal_positivos |>
  ggplot(aes(x = positivos)) +
  geom_histogram(bins = 82) +
  ggtitle("Casos Positivos en Cantones") +
  xlab("Casos") +
  ylab("Frecuencia") +
  labs(subtitle = "Datos")

# Histograma plotly
ggplotly(histograma_ggplot2) |> 
  config(locale = 'es')
```

